"""Generate src/pokerbot/strategy/preflop_strength.py.

Computes each 169 starting-hand class's heads-up all-in equity vs a uniformly random
hand via Monte-Carlo, then writes an embedded dict so decision-time has zero MC cost for
preflop ranking. Run once (or when you want to regenerate):

    PYTHONPATH=src ./.venv/bin/python tools/gen_preflop_strength.py
"""
from __future__ import annotations

import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from pokerbot.equity.montecarlo import equity  # noqa: E402
from pokerbot.strategy.notation import all_hand_classes, representative_cards  # noqa: E402

ITERATIONS = 40_000
SEED = 20260604
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "pokerbot", "strategy",
                   "preflop_strength.py")


def main() -> None:
    rng = random.Random(SEED)
    rows = []
    for i, cls in enumerate(all_hand_classes(), 1):
        eq = equity(representative_cards(cls), [], 1, iterations=ITERATIONS, rng=rng)
        rows.append((cls, round(eq, 4)))
        print(f"\r{i:3d}/169  {cls:4s} {eq:.4f}", end="", flush=True)
    print()
    rows.sort(key=lambda r: r[1], reverse=True)

    lines = [
        "# AUTO-GENERATED by tools/gen_preflop_strength.py — do not edit by hand.",
        f"# Heads-up all-in equity vs a uniformly random hand (Monte-Carlo, "
        f"{ITERATIONS} iters, seed {SEED}).",
        "PREFLOP_EQUITY: dict[str, float] = {",
    ]
    for cls, eq in rows:
        lines.append(f'    "{cls}": {eq},')
    lines.append("}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {len(rows)} classes -> {OUT}")
    print(f"best:  {rows[0]}   worst: {rows[-1]}")


if __name__ == "__main__":
    main()
